### ISSUE TITLE
Installing by the readme - gives the following errors

### ISSUE THREAD

**Issue by jj33** [ronschaeffer/sbm2mqtt#18]
Followed the readme setup instructions to install on a pi0w, fresh install of buster lite.

pi@raspberrypi:~/switchbot $ uname -a
Linux raspberrypi 5.10.17+ #1414 Fri Apr 30 13:16:27 BST 2021 armv6l GNU/Linux

pi@raspberrypi:~/switchbot $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
pi@raspberrypi:~/switchbot $

pi@raspberrypi:~/switchbot $ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

pi@raspberrypi:~/switchbot $ sudo apt install python3-pip libglib2.0-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libglib2.0-dev is already the newest version (2.58.3-2+deb10u2).
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

pi@raspberrypi:~/switchbot $ sudo pip3 install bluepy
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: bluepy in /usr/local/lib/python3.7/dist-packages (1.3.0)

pi@raspberrypi:~/switchbot $ sudo pip3 install paho-mqtt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: paho-mqtt in /usr/local/lib/python3.7/dist-packages (1.5.1)

Scanning for SwitchBot Meters...
Traceback (most recent call last):
  File "/home/pi/switchbot/sbm2mqtt.py", line 107, in <module>
    main()
  File "/home/pi/switchbot/sbm2mqtt.py", line 101, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'le on' (code: 17, error: Invalid Index)

**Comment by jj33** [comment]
Fixed via reboot, apologies! I'll leave the issue in case someone runs across it in the future.
