### ISSUE TITLE
trouble when running script

### ISSUE THREAD

**Issue by WorldsWorstAstronaut** [ronschaeffer/sbm2mqtt#26]
I think I have everything set up properly, but I keep getting an error when I run the sbm2mqtt.py script. 
I've included what gets returned in terminal when I run it. It looks like the script pulls the data from the meter, but doesn't pass it on to mqtt. Any help with this would be great, I seem to be out of my element on this one.

Scanning for SwitchBot Meters...

e6:c5:32:dd:dd:27 @ 2023-06-19 16:45:48
  Temp: 70.3°F
  Humidity: 54%
  Battery: 69%

  Publishing MQTT payload to wetter/act-temp/e6:c5:32:dd:dd:27 ...

    {"time": "2023-06-19 16:45:48", "temperature": 70.3, "humidity": 54, "battery": 69, "temperature_scale": "F", "signal_strength": -76}
Traceback (most recent call last):
  File "/home/pi/switchbot/sbm2mqtt.py", line 106, in <module>
    main()
  File "/home/pi/switchbot/sbm2mqtt.py", line 100, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 853, in scan
    self.process(timeout)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 842, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "/home/pi/switchbot/sbm2mqtt.py", line 92, in handleDiscovery
    mqttc.connect(mqtt_host, mqtt_port)
  File "/usr/local/lib/python3.9/dist-packages/paho_mqtt-1.6.1-py3.9.egg/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho_mqtt-1.6.1-py3.9.egg/paho/mqtt/client.py", line 1045, in reconnect
    on_pre_connect = self.on_pre_connect
  File "/usr/local/lib/python3.9/dist-packages/paho_mqtt-1.6.1-py3.9.egg/paho/mqtt/client.py", line 1863, in on_pre_connect
    return self._on_pre_connect
AttributeError: 'Client' object has no attribute '_on_pre_connect'

**Comment by WorldsWorstAstronaut** [comment]
This can be closed. I went a different route.

**Comment by ronschaeffer** [comment]
Sorry for the slow reply. Thanks for letting me know.
