### ISSUE TITLE
New Bug after reinstall

### ISSUE THREAD

**Issue by GreenBear33** [ronschaeffer/sbm2mqtt#6]
HI Ron, 

Due to a crash of my pi, I had to reinstall everything. 

I went through the same steps but am now getting some issues with it. Here is the fault I am getting when running sbm2mqtt.py.

```
Scanning for SwitchBot Meters...

Finished.


Scanning for SwitchBot Meters...

d1:49:4a:73:93:99 @ 2020-06-12 00:18:05
  Temp: 26.8°C
  Humidity: 75%
  Battery: 100%

  Publishing MQTT payload to switchbot_meter/d1:49:4a:73:93:99 ...

    {"time":"2020-06-12 00:18:05","temperature":26.8,"humidity":75,"battery":100,"temperature_scale":"C"}
Traceback (most recent call last):
  File "/home/pi/Switchbot/sbm2mqtt.py", line 115, in <module>
    main()
  File "/home/pi/Switchbot/sbm2mqtt.py", line 109, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 853, in scan
    self.process(timeout)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 842, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "/home/pi/Switchbot/sbm2mqtt.py", line 101, in handleDiscovery
    mqttc.connect(mqtt_host, mqtt_port)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

I thought I did everything the same but when I try to run `sudo python 3 sbm2mqtt.py` it tells me that no file is in the folder. Previously I could run it like that without a problem but this time I have to run it like this `sudo python3 /home/pi/switchbot/sbm2mqtt.py`, could this have something to do with the problem?

Hopefully you can help. 

Many thanks.

**Comment by GreenBear33** [comment]
I fixed this again myself. I forgot to install mosquitto mqtt broker, now it works.

**Comment by macandriu** [comment]
Hi! I am having a similar problem. Could you post your sbm2mqtt_configuration file and the Mosquitto configuration? I have some doubts with the users declared and so on.

Thanks!
