### ISSUE TITLE
Script raises BTLEManagementError

### ISSUE THREAD

**Issue by BernierMaxence1** [ronschaeffer/sbm2mqtt#7]
Hi,

First, thank you for sharing this ! 

I am have into an error when running sbm2mqtt
```
$ python3 sbm2mqtt.py
```

This error mentions permission problems, but I am logged in as root, and running with `sudo`does not fix it. Here is the error : 
```sh
Scanning for SwitchBot Meters...
Traceback (most recent call last):
  File "sbm2mqtt.py", line 115, in <module>
    main()
  File "sbm2mqtt.py", line 109, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 790, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 309, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 366, in _waitResp
    raise BTLEManagementError("Management not available (permissions problem?)", resp)
bluepy.btle.BTLEManagementError: Management not available (permissions problem?) 
```

I am running this in a python:3.8.5-slim-buster docker container. 

I have search for this error and was not able to find a solution. Have you ever run into the same error ? Do you have any leads for me ? Thank you so much for your help. 

Maxence

**Comment by ronschaeffer** [comment]
Sorry for the delay in responding. I haven't seen that before.

I'm certainly not a docker expert, but it may be an issue with access to Bluetooth inside the container. Does `service bluetooth status` inside the container show that the Bluetooth service is active? Does sbm2mqtt run successfully on the host (not in the container)?

**Comment by tullyz** [comment]
sudo python3 sbm2mqtt.py 
might work.

**Comment by thematrixdev** [comment]
I have got a similiar error. I am running it on Ubuntu 20.04 on Odyssey x86j4105.

`sudo python3 sbm2mqtt.py 

Scanning for SwitchBot Meters...
Traceback (most recent call last):
  File "sbm2mqtt.py", line 115, in <module>
    main()
  File "sbm2mqtt.py", line 109, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 854, in scan
    self.stop()
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 803, in stop
    self._mgmtCmd(self._cmd()+"end")
  File "/usr/local/lib/python3.8/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend' (code: 11, error: Rejected)`

@BernierMaxence1 have you found any solution to your problem?

**Comment by ronschaeffer** [comment]
Any luck sorting out the error?

I can't think of anything specific to suggest. But I did have a lot of problems at the beginning related to dependencies. You may want to try installing dependencies again and/or starting from a fresh image.

I have not tested this with Ubuntu.

**Comment by GreenBear33** [comment]
Hi Ron, 

Everything was working fine for 6 months until this morning when I started getting the same error as above. Nothing has changed and I am not sure where to go from here. Can you please help. 

The error code I am getting is:

```
Scanning for SwitchBot Meters...
Traceback (most recent call last):
  File "/home/pi/switchbot/sbm2mqtt.py", line 115, in <module>
    main()
  File "/home/pi/switchbot/sbm2mqtt.py", line 109, in main
    scanner.scan(10.0)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 852, in scan
    self.start(passive=passive)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 800, in start
    self._mgmtCmd(self._cmd())
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (cmd), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scan'
```
Any help would be greatly appreciated.

**Comment by eeezyy** [comment]
For me it works on Ubuntu 20.04. 
But have the same problem when running it in Docker.
I see there is a PullRequest for a docker implementation, did not try it out yet, but looks promising :)

**Comment by ronschaeffer** [comment]
> I see there is a PullRequest for a docker implementation, did not try it out yet, but looks promising :)

I've got a working Docker container based mostly on the pull request. I just need to allocate some time to tidy things up before posting here.
